env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:github/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - github
  - prettier
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  react/react-in-jsx-scope:
    - off
  react/jsx-uses-react:
    - off
  github/no-then:
    - off
  filenames/match-regex:
    - off
  import/extensions:
    - off
  no-unused-vars:
    - off
  '@typescript-eslint/no-unused-vars':
    - error
  import/named:
    - off
  no-shadow:
    - off
  '@typescript-eslint/no-shadow':
    - error
