name: Test Code on commit
on: push
jobs:
  validate-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run prettier
  
  # validate-eslint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run:
  #         npm run eslint
  validate-build:
    runs-on: ubuntu-latest
    needs: [validate-prettier]
    steps:
      - uses: actions/checkout@v3
      - run:
          npm run build
